export const usageGuidelines = [
  {
    do: "Use Halaney only for specific emotional moments (welcome, match, seller stories)",
    dont: "Use Halaney on buttons, labels, prices, or any functional text",
  },
  {
    do: "Use a maximum of 2 headline levels per screen",
    dont: "Mix more than 2 headline sizes in a single view — it breaks the hierarchy",
  },
  {
    do: "Use bold weight to emphasize text within a paragraph",
    dont: "Use underline for emphasis — it gets confused with a link",
  },
  {
    do: "Keep Halaney phrases short (1–5 words)",
    dont: "Put a long sentence in Halaney — legibility drops fast in a script typeface",
  },
  {
    do: "Left-align reading text",
    dont: "Center-align long paragraphs — harder to read, especially for users with dyslexia",
  },
] as const

export const typeScale = [
  {
    style: "Headline 1",
    role: "Hero",
    token: "matchy-heading-1",
    className: "matchy-heading-1",
    font: "Degular",
    weight: "Bold",
    size: "32px",
    letterSpacing: "-1%",
    lineHeight: "32",
    sample: "Matchy",
  },
  {
    style: "Headline 2",
    role: "Section",
    token: "matchy-heading-2",
    className: "matchy-heading-2",
    font: "Degular",
    weight: "Bold",
    size: "24px",
    letterSpacing: "-1%",
    lineHeight: "32",
    sample: "Foundations",
  },
  {
    style: "Label 1",
    role: "Default label",
    token: "matchy-label-1",
    className: "matchy-label-1",
    font: "Degular",
    weight: "Regular",
    size: "16px",
    letterSpacing: "0%",
    lineHeight: "16",
    sample: "Price",
  },
  {
    style: "Label 2",
    role: "Emphasized label",
    token: "matchy-label-2",
    className: "matchy-label-2",
    font: "Degular",
    weight: "Bold",
    size: "16px",
    letterSpacing: "0%",
    lineHeight: "16",
    sample: "In stock",
  },
  {
    style: "Label 3",
    role: "Metadata",
    token: "matchy-label-3",
    className: "matchy-label-3",
    font: "Degular",
    weight: "Bold",
    size: "14px",
    letterSpacing: "0%",
    lineHeight: "16",
    sample: "Second hand",
  },
  {
    style: "Paragraph 1",
    role: "Body text",
    token: "matchy-paragraph",
    className: "matchy-paragraph",
    font: "Degular",
    weight: "Regular",
    size: "16px",
    letterSpacing: "0%",
    lineHeight: "24",
    sample: "Clear, scannable reading text at the accessibility minimum.",
  },
  {
    style: "Button",
    role: "Primary action",
    token: "matchy-button-primary",
    className: "matchy-button-primary",
    font: "Degular",
    weight: "Bold",
    size: "16px",
    letterSpacing: "0%",
    lineHeight: "16",
    sample: "Continue",
  },
  {
    style: "Button 2",
    role: "Compact action",
    token: "matchy-button-secondary",
    className: "matchy-button-secondary",
    font: "Degular",
    weight: "Bold",
    size: "12px",
    letterSpacing: "0%",
    lineHeight: "16",
    sample: "Save",
  },
  {
    style: "Emotional Large",
    role: "Match moment",
    token: "matchy-emotional-lg",
    className: "matchy-emotional-lg",
    font: "Halaney",
    weight: "Regular",
    size: "32px",
    letterSpacing: "0%",
    lineHeight: "40",
    sample: "It's a match",
  },
  {
    style: "Emotional Small",
    role: "Welcome",
    token: "matchy-emotional-sm",
    className: "matchy-emotional-sm",
    font: "Halaney",
    weight: "Regular",
    size: "20px",
    letterSpacing: "0%",
    lineHeight: "32",
    sample: "Welcome",
  },
] as const

export const degularStyles = typeScale.filter((style) => style.font === "Degular")
export const halaneyStyles = typeScale.filter((style) => style.font === "Halaney")
